export interface Video {
  id: string;
  collection_id: string;
  video_id: string;
  worker_id: string;
  task_type: string[];
  normalized_tags: string[];
  duration_minutes: number;
  video_length: string;
  environment: string;
  recording_date: string;
  video_url: string;
  thumbnail_url: string;
  file_size: string;
  resolution: string;
  frame_rate: string;
  audio_quality: string;
  hands_visible: boolean;
  lighting_quality: string;
  pii_check_status: string;
  qa_status: string;
}

export interface Collection {
  id: string;
  organization_id: string;
  title: string;
  description: string;
  cover_image_url: string;
  tags: string[];
  is_published: boolean;
}

export const MOCK_VIDEOS: Video[] = [
  {
    id: "uuid-1",
    collection_id: "col-1",
    video_id: "VID_001",
    worker_id: "RANI_W622",
    task_type: ["Making Tea"],
    normalized_tags: ["tea_preparation"],
    duration_minutes: 8,
    video_length: "0:08:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-02",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1576092762791-dd9e2220afa1?q=80&w=640&auto=format&fit=crop",
    file_size: "1.2 GB",
    resolution: "1080p",
    frame_rate: "60fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-2",
    collection_id: "col-1",
    video_id: "VID_002",
    worker_id: "RANI_W622",
    task_type: ["Cooking", "Cutting Veg", "Dishwashing"],
    normalized_tags: ["meal_preparation", "vegetable_cutting", "dishwashing"],
    duration_minutes: 16,
    video_length: "0:16:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-02",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=640&auto=format&fit=crop",
    file_size: "3.73 GB",
    resolution: "1080p",
    frame_rate: "60fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-3",
    collection_id: "col-1",
    video_id: "VID_003",
    worker_id: "RANI_W622",
    task_type: ["Dishwashing", "Kitchen Cleaning"],
    normalized_tags: ["dishwashing", "kitchen_cleaning"],
    duration_minutes: 4,
    video_length: "0:04:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-02",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1584824486516-0555a07fc511?q=80&w=640&auto=format&fit=crop",
    file_size: "0.8 GB",
    resolution: "1080p",
    frame_rate: "60fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-4",
    collection_id: "col-1",
    video_id: "VID_004",
    worker_id: "RANI_W1152",
    task_type: ["Dishwashing", "Laundry", "Kitchen Cleaning"],
    normalized_tags: ["dishwashing", "laundry", "kitchen_cleaning"],
    duration_minutes: 15,
    video_length: "0:15:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-03",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?q=80&w=640&auto=format&fit=crop",
    file_size: "2.5 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "Blurred Required",
    qa_status: "Pending",
  },
  {
    id: "uuid-5",
    collection_id: "col-1",
    video_id: "VID_005",
    worker_id: "RANI_W1152",
    task_type: ["Hanging Clothes"],
    normalized_tags: ["clothes_hanging"],
    duration_minutes: 1,
    video_length: "0:01:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-03",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?q=80&w=640&auto=format&fit=crop",
    file_size: "0.15 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "Blurred Required",
    qa_status: "Pending",
  },
  {
    id: "uuid-6",
    collection_id: "col-1",
    video_id: "VID_006",
    worker_id: "RANI_W1152",
    task_type: ["Hanging Clothes", "Bed Making"],
    normalized_tags: ["clothes_hanging", "bed_making"],
    duration_minutes: 1,
    video_length: "0:01:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-03",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=640&auto=format&fit=crop",
    file_size: "0.2 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-7",
    collection_id: "col-1",
    video_id: "VID_007",
    worker_id: "RANI_W1226",
    task_type: ["Dishwashing", "Utensil Org", "Kitchen Cleaning", "Cooking"],
    normalized_tags: ["dishwashing", "utensil_organization", "kitchen_cleaning", "meal_preparation"],
    duration_minutes: 8,
    video_length: "0:08:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-04",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=640&auto=format&fit=crop",
    file_size: "1.3 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-8",
    collection_id: "col-1",
    video_id: "VID_008",
    worker_id: "RANI_W1226",
    task_type: ["Laundry", "Hanging Clothes"],
    normalized_tags: ["laundry", "clothes_hanging"],
    duration_minutes: 6,
    video_length: "0:06:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-04",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1604335398980-ced0b7c3d22b?q=80&w=640&auto=format&fit=crop",
    file_size: "1.0 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-9",
    collection_id: "col-1",
    video_id: "VID_009",
    worker_id: "RANI_W1226",
    task_type: ["Hanging Clothes", "Mopping"],
    normalized_tags: ["clothes_hanging", "floor_cleaning"],
    duration_minutes: 5,
    video_length: "0:05:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-04",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1584824486539-53bb4646bdbc?q=80&w=640&auto=format&fit=crop",
    file_size: "0.9 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-10",
    collection_id: "col-1",
    video_id: "VID_010",
    worker_id: "RANI_W951",
    task_type: ["Cooking", "Dishwashing", "Kitchen Clean", "Laundry", "Utensil Org"],
    normalized_tags: ["meal_preparation", "dishwashing", "kitchen_cleaning", "laundry", "utensil_organization"],
    duration_minutes: 31,
    video_length: "0:31:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-05",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1556911261-6bd341186b2f?q=80&w=640&auto=format&fit=crop",
    file_size: "5.2 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-11",
    collection_id: "col-1",
    video_id: "VID_011",
    worker_id: "RANI_W1081",
    task_type: ["Dishwashing", "Kitchen Cleaning", "Utensil Org"],
    normalized_tags: ["dishwashing", "kitchen_cleaning", "utensil_organization"],
    duration_minutes: 3,
    video_length: "0:03:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-05",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=640&auto=format&fit=crop",
    file_size: "0.5 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  },
  {
    id: "uuid-12",
    collection_id: "col-1",
    video_id: "VID_012",
    worker_id: "RANI_W1081",
    task_type: ["Dishwashing", "Cutting Vegetables"],
    normalized_tags: ["dishwashing", "vegetable_cutting"],
    duration_minutes: 11,
    video_length: "0:11:00",
    environment: "Urban 1RK",
    recording_date: "2025-12-05",
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1615887023516-90aaacafffc7?q=80&w=640&auto=format&fit=crop",
    file_size: "2.1 GB",
    resolution: "1080p",
    frame_rate: "30fps",
    audio_quality: "Good",
    hands_visible: true,
    lighting_quality: "Good",
    pii_check_status: "No PII",
    qa_status: "Verified",
  }
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    organization_id: "org-1",
    title: "Kitchen Activities — December 2025",
    description: "Curated egocentric footage of various kitchen tasks including cooking, dishwashing, and cleaning in urban environments.",
    cover_image_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&q=80",
    tags: ["kitchen", "cooking", "urban"],
    is_published: true,
  }
];
